spring.application.name=fleetflow-backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/fleetflow
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

jwt.secret=8e0f4c9b2f1d7a6e5c4b3a2918171615141312110ffeeddccbbaa99887766554433221100ffeeddccbbaa998877665544
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000